#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

APP="$1";
# Load configuration to be available
eval "$(config_export app "$APP")"

HOOKS_DIR=${HOOKS_DIR:-hooks}

dokku_log_info1 "Checking for pre-build script in $HOOKS_DIR"
if [ -f "$HOOKS_DIR/pre-build" ]; then
    if [ ! -x "$HOOKS_DIR/pre-build" ]; then
        dokku_log_warn "Adding missing execution permission. Please check your permissions."
        chmod +x $HOOKS_DIR/pre-build
    fi
     dokku_log_info2 "Running pre-build script"
     $HOOKS_DIR/pre-build
     dokku_log_info2 "End of pre-build script"
fi